### ISSUE TITLE
Results from the test phase

### ISSUE THREAD

**Issue by pdehaye** [admin-ch/PT-System-Documents#1]
Results from the test phase were promised a long time ago. Where are they?

**Comment by cedricmoullet** [comment]
Final risk report has been published on 24.6.2020:
https://www.melani.admin.ch/dam/melani/de/dokumente/2020/20200624_Final_Risk_Report_PST_NCSC-sig.pdf.download.pdf/20200624_Final_Risk_Report_PST_NCSC-sig.pdf
