### ISSUE TITLE
Difference between test phase and "production"

### ISSUE THREAD

**Issue by pdehaye** [admin-ch/PT-System-Documents#2]
During the test phase, I think the thresholds chosen were `[50, 55]`. The same thresholds are now applicable for the "production" phase, despite the [SwissCovid-ExposureScore.pdf](https://github.com/admin-ch/PT-System-Documents/blob/master/SwissCovid-ExposureScore.pdf) document and test phase documents giving the impression something has changed in the intent to notify, going from 2m to 1.5m. 

Indeed, [this document](https://www.newsd.admin.ch/newsd/message/attachments/61311.pdf) regarding the test phase said (similar statements are repeated multiple times): 
> Elle n’avertit les utilisateurs d’une contamination potentielle qu’à partir du moment où un utilisateur infecté s’est trouvé à moins de 2 mètres d’eux pendant 15minutes, la présomption d’une transmission du virus étant alors suffisamment importante.

On the other hand, the [SwissCovid-ExposureScore.pdf](https://github.com/admin-ch/PT-System-Documents/blob/master/SwissCovid-ExposureScore.pdf) document refers to the Ordinance of 6/25 to mention the distance of 1.5m ([Annex](https://www.admin.ch/opc/fr/classified-compilation/20201730/index.html)). 

An explanation would be that the test phase was aiming for 2m, and coincidentally chose the exact parameters needed for 1.5m, which happened to be the final decision of the Federal Council. Is this what happened?

**Comment by cedricmoullet** [comment]
The SwissCovid-ExposureScore.pdf has been updated and informs about the current situation and thresholds.
