### ISSUE TITLE
False TEKs published to server?

### ISSUE THREAD

**Issue by pdehaye** [admin-ch/PT-System-Documents#5]
The TEK server seems to publish 10 TEKs per day almost every day for now. I observe however that one day 11 TEKs were published, and that there might be other deviations more recently. 

My assumption is that this is a weak form of privacy protection, as also surmized by an [Irish team](https://down.dsg.cs.tcd.ie/tact/transp.pdf) (see also [here](https://down.dsg.cs.tcd.ie/tact/tek-counts/)). 

It would be important however for transparency to know how many of those keys are genuine (without necessarily knowing which). Would you expect a privacy impact from this?

**Comment by pdehaye** [comment]
Extracting the TEKs submitted to the central server, we can see that they are _all_ set to a risk level of 0. 
This seems, [in the Google spec](https://blog.google/documents/68/Android_Exposure_Notification_API_documentation_v1.2.pdf), to correspond to RISK_LEVEL_INVALID. I know that SwissCovid's usage of the API is unorthodox, but is this correct?

**Comment by pdehaye** [comment]
To expand a bit on what was said in the first post, on every day since the first day there are 10 TEKs, except for some days, where there is an **excess** to those 10 TEKs:
```
Time: 2020-06-26 02:00:00 CEST - 2020-06-27 02:00:00 CEST (2655216, 144) * 1
Time: 2020-06-29 02:00:00 CEST - 2020-06-30 02:00:00 CEST (2655648, 144) * 12
Time: 2020-06-30 02:00:00 CEST - 2020-07-01 02:00:00 CEST (2655792, 144) * 9
Time: 2020-07-01 02:00:00 CEST - 2020-07-02 02:00:00 CEST (2655936, 144) * 6
```
What is surprising to me is that it is the same day of validity for *all* the keys that get uploaded the same day. 

Given what I understand of the configuration, it would mean that there are between 19 and 29 SwissCovid users who have tested positive so far (that seems very large), AND that all those users got infected within one day of installing the app. That seems extraordinarily unlikely.

**Comment by pdehaye** [comment]
Some more "insight": the TEK files being published actually change over time. For instance [what the Irish team has](https://down.dsg.cs.tcd.ie/tact/tek-counts/) is very different from what I have. 

In fact, the TEK files that are published seem to change, with new keys added over time but also _some being removed_. Since those removed actually seem to be replaced, it could be that those are the fake TEKs being added. 

Could you clarify what is going on here?

**Comment by cedricmoullet** [comment]
Fake TEKs are not published anymore: https://www.melani.admin.ch/melani/de/home/public-security-test/current_findings.html
