### ISSUE TITLE
"[..] this exposure check occurs several times a day [..]"

### ISSUE THREAD

**Issue by pdehaye** [admin-ch/PT-System-Documents#6]
The Exposure Score calculation document states:

> In the SwissCovid app, this exposure check occurs several times a day and utilizes exposures from the current day and the 9 immediately preceding days. 

I think this is misleading. Several means (in my book) more than two. In reality this check occurs twice per day, AFAICT.

**Comment by r-r-liu** [comment]
Nope. I am a native speaker of Murcan (American English). Several is two or more.
