### ISSUE TITLE
Following our phone call

### ISSUE THREAD

**Issue by pdehaye** [admin-ch/PT-System-Documents#7]
After posting the first five issues, I got a phone call. I didn't catch the name of the person on the other side, but know this person watches this repository. 

Since some of my references seemed to be interesting to them, here they are:
* [_A mathematical assessment of the efficiency of quarantining and contact tracing in curbing the COVID-19 epidemic_](https://www.medrxiv.org/content/10.1101/2020.05.04.20091009v1), which I expanded on [here](https://twitter.com/podehaye/status/1277590129465610240?s=20) with specific Swiss parameters. 
* [_A Coronavirus Contact Tracing App Replay Attack with Estimated Amplification Factors_](https://down.dsg.cs.tcd.ie/tact/replay.pdf)
* [_Quantifying Surveillance in the Networked Age: Node-based Intrusions and Group Privacy_](https://arxiv.org/abs/1803.09007)
* [_SwissCovid: a critical analysis of risk assessment by Swiss authorities_](https://arxiv.org/abs/2006.10719)

These references either touch to the utility of the app, or the potential for misuse.

**Comment by cedricmoullet** [comment]
Thanks for sharing !
